[theme]
primaryColor = "#E85B4F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FAFAFA"
textColor = "#111111"
font = "sans serif"

[client]
showErrorDetails = true

[logger]
level = "info"

[ui]
hideTopBar = false
hideSidebarNav = false

[browser]
gatherUsageStats = false
